services:
  gzclient:
    image: gazebo9
    build: ./builds/visualization-client/
    environment:
      - DISPLAY=$DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XAUTHORITY=$XAUTHORITY 
      # - GAZEBO_MASTER_URI="http://172.18.0.2:11345"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    runtime: nvidia

### give docker containers (clients) access the X11 display on the host machine
# $: xhost +